### ISSUE TITLE
Support multiple tests for the same control_id

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/rspec_oscal_formatter#1]
As a developer, I want to write multiple tests for the same control_id, so I can validate each piece of functionality separately and get OSCAL output for all tests combined into one file.
```[tasklist]
### Tasks
- [x] Add additional spec tests for existing functionality
- [x] Investigate if generating an assessment plan and result for each separate control_id is the best approach
- [x] Collate multiple tests into 1 results file.
```
